name: Request a new command
description: Suggest an command for this project
title: "[New Command]: /<command category> [command_group] <command_name> "
labels: ["enhancement", "new-command"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: category
    attributes:
      label: Category
      description: Where should we put this command?
      placeholder: ex. /*fun*
    validations:
      required: true
  - type: input
    id: group
    attributes:
      label: Group
      description: Does this command belong to this group?
      placeholder: ex. /manage *credits* give
  - type: textarea
    id: description
    attributes:
      label: What should the command do?
      description: Please tell us your concept, how it should work, and if there should be any additional features.
      placeholder: "I would like to have a meme command, that would make my members laugh and communicate more! I would like it to gather memes from the subreddit r/memes. And display the image with the title and up/down votes."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
