name: Command request
description: Suggest an command for this project
title: "[Command]: "
labels: ["enhancement", "command"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: category
    attributes:
      label: Category
      description: Where should we put this command?
      placeholder: ex. /fun
      value: "/"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What should the command do?
      description: Please tell us your concept, how it should work, and if there should be any additional features.
      placeholder: "I would like to have a meme command, that would make my members laugh and communicate more! I would like it to gather memes from the subreddit r/memes. And display the image with the title and up/down votes."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
